In [1]:
import numpy as np
print(np.__version__)

2.3.3


In [42]:
print("creating a array using numpy")
print("1)1D array \n2)2D array\n3)3D array")

creating a array using numpy
1)1D array 
2)2D array
3)3D array


In [4]:
print("1D array")  #1-D array
arr1D = np.array([1,2,3,4,5])
print(arr1D, type(arr1D))

1D array
[1 2 3 4 5] <class 'numpy.ndarray'>


In [16]:
print("2D array")  #2-D array
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D, type(arr2D))

2D array
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [69]:
print("3D array")  #3-D array
arr3D = np.array([[[1,2],[3,4],[5,6]]])
print(arr3D, type(arr3D))

3D array
[[[1 2]
  [3 4]
  [5 6]]] <class 'numpy.ndarray'>


In [22]:
print("\n ---> attributes of arrays:")
print("\n1)size \n2)shape \n3)dtype \n4)ndim")


 ---> attributes of arrays:

1)size 
2)shape 
3)dtype 
4)ndim


In [23]:
print("1)size : it return number of element array contain")

1)size : it return number of element array contain


In [37]:
arr1D = np.array([1,2,3,4,5])  # size work same as length
print(arr1D)
print("size is:",arr1D.size)
print("length is:",len(arr1D))

[1 2 3 4 5]
size is: 5
length is: 5


In [38]:
print("2D array")
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D)
print("size is:",arr2D.size)

2D array
[[1 2 3]
 [4 5 6]]
size is: 6


In [70]:
print("3D array")
arr3D = np.array([[[1,2],[3,4],[5,6]]])
print(arr3D)
print("size is:", arr3D.size)

3D array
[[[1 2]
  [3 4]
  [5 6]]]
size is: 6


In [77]:
print("shape:- it return tuple of one or more element ")
print("---it return number of rows and column")

shape:- it return tuple of one or more element 
---it return number of rows and column


In [72]:
arr1D = np.array([1,2,3,4,5,6]) 
print(arr1D)
arr1D.shape

[1 2 3 4 5 6]


(6,)

In [73]:
arr2D = np.array([[1,2,3],  # 2 is a number of row
                  [4,5,6]]) # 3 is a number of column
print(arr2D)
arr2D.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [79]:
arr3D = np.array([[1, 2],
                  [3, 4],
                  [5, 6]]) 
                        # 3 is a number of row
print(arr3D)            # 2 is a number of column
arr3D.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [82]:
arr = np.array([[[1,2,3],
                 [4,5,6]]]) # 1 is a layer
                            # 2 is a row
                            # 3 is a column
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]]


(1, 2, 3)

In [90]:
print("dtype: it return size depends on system")

dtype: it return size depends on system


In [99]:
arr1 = np.array([1,2,3,4,5])
arr1.dtype

dtype('int64')

In [109]:
print("ndim:")

ndim:


In [116]:
x = np.array([55,4,2,4])
x.ndim


1