# create a 2D array

In [1]:
lst = [[10, 20, 30],[40, 50, 60]]
print(lst)

[[10, 20, 30], [40, 50, 60]]


In [5]:
import numpy as np

In [11]:
x = np.array(lst)
print(x)

[[10 20 30]
 [40 50 60]]


In [17]:
#[40, 50, 60] access only this line

In [49]:
x[1::,1] #access 50

array([50])

In [57]:
x[0:2, 0:2]

array([[10, 20],
       [40, 50]])

In [63]:
x[1,2::]

array([60])

# create 3D array

In [77]:
import numpy as np

In [82]:
a = np.arange(12)

In [85]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [87]:
x = np.arange(24)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [95]:
y = x.reshape(3,2,4)
print(y)
np.shape(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


(3, 2, 4)

# indexing
### y[layer]
### y[layer, row]
### y[layer, row, column]

In [96]:
# access first layer
y[0] 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [100]:
# access last layer
y[-1]
y[2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [102]:
# access middle layer
y[1]
y[-2]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [107]:
# first raw second layer
y[1,0]

array([ 8,  9, 10, 11])

In [109]:
# first 2 layer
y[0:2]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [111]:
#reverse a layer
y[::-1]

array([[[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]]])

# Slicing


In [113]:
# x[layer_slicing]
# x[start:stop:step]

# x[layer_slicing, raw_slicing]
# x[start:stop:step, start:stop:step]

# x[layer_slicing, raw_slicing, column_slicing]
# x[start:stop:step, start:stop:step, start:stop:step]

In [115]:
c = np.arange(36)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [119]:
d = c.reshape(4,3,3)
print(d)  

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]


In [123]:
# layer_slicing
# x[start:stop:step]
#access first 2 layer
d[0:2:]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [137]:
#access last 2 layers
d[2:4:]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [138]:
#access only second layer
d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [139]:
# x[layer_slicing, raw_slicing]
# x[start:stop:step, start:stop:step]
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [141]:
#second layers second raw
d[1,1]

array([12, 13, 14])

In [143]:
#fourth layers third raw
d[3,2]

array([33, 34, 35])

In [146]:
#third layer first raw
d[2,0]

array([18, 19, 20])

In [147]:
# x[layer_slicing, raw_slicing, column_slicing]
# x[start:stop:step, start:stop:step, start:stop:step]
d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [152]:
#access 4
d[0, 1, 1]

np.int64(4)

In [155]:
#access 15
d[1,2,0]

np.int64(15)

In [158]:
#access 35
d[3, 2, 2]

np.int64(35)

In [162]:
# [22:23]
d[2, 1, 1::]

array([22, 23])

In [175]:
# [16,17]
# [25,26]
d[1:3, 2::, 1::]

array([[[16, 17]],

       [[25, 26]]])

In [184]:
# [3:5]
# [30:32]
d[0:4:3, 1:2:1, 0:3:2]

array([[[ 3,  5]],

       [[30, 32]]])

In [189]:
q = np.arange(48)
print(q)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [196]:
r = q.reshape(6,2,4)
print(r)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]]


In [203]:
# [20:21]
# [44:45]
r[2:6:3, 1::, 0:2]

array([[[20, 21]],

       [[44, 45]]])

In [227]:
# [1:2]
# [41:42]
r[0:6:5, 0, 1:3:1]

array([[ 1,  2],
       [41, 42]])

In [228]:
# [12:15]
# [44:47]
r[1:6:4, 1, 0::3]

array([[12, 15],
       [44, 47]])

In [231]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [241]:
# [1:2:3]
# [33:34:35]
r[0:5:4, 0, 1:]

array([[ 1,  2,  3],
       [33, 34, 35]])